services:
  keydb:
    image: eqalpha/keydb
    container_name: keydb
    # ports:   # Not needed for macvlan
    #   - "6379:6379"
    #   - "8080:8080"
    volumes:
      - keydb:/data
    labels:
      - "coredns.dockerdiscovery.host=key.home"
    dns:
      - 192.168.40.5
    networks:
      app-network:
        ipv4_address: 192.168.40.13

volumes:
  keydb:

networks:
  app-network:
    external: true
