services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    volumes:
      - open-webui-data:/app/backend/data
    environment:
      - PORT=80
      - ADMIN_EMAIL=bill.baran@gmail.com
    labels:
      - "coredns.dockerdiscovery.host=llm.home"
    dns:
      - 192.168.40.5
    networks:
      app-network:
        ipv4_address: 192.168.40.10

volumes:
  open-webui-data:
    external: true

networks:
  app-network:
    external: true
