serverAddr = "{{ .Envs.FRP_HOST }}"
serverPort = 7000
#log.to = "/var/log/frpc.log"
log.level = "info"
transport.tls.enable = true
transport.tls.certFile = "/etc/frp/certs/client.crt"
transport.tls.keyFile = "/etc/frp/certs/client.key"
transport.tls.trustedCaFile = "/etc/frp/certs/ca.crt"
auth.token = "{{ .Envs.FRP_AUTH_TOKEN }}"

[[proxies]]
name = "telegram-bot"
type = "http"
localIP = "n8n.home"
localPort = 80
customDomains = ["{{ .Envs.BOT_DOMAIN  }}"]
