services:
  qdrant:
    image: qdrant/qdrant:v1.13.4
    container_name: qdrant
#    ports:   # Don't need ports when using macvlan
#      - "6333:6333"
#      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    dns:
      - 192.168.40.5
    networks:
      app-network:
        ipv4_address: 192.168.40.4

networks:
  app-network:
    external: true

volumes:
  qdrant_data:
    external: true
