services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.8.0
    container_name: mealie
    restart: always
    #ports:
    #    - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      - ALLOW_SIGNUP
      #- PUID=1000
      #- PGID=1000
      - TZ
      - BASE_URL
      - API_PORT=80
      - OPENAI_API_KEY
      - DB_ENGINE=postgres
      - POSTGRES_USER=mealie
      - POSTGRES_PASSWORD=mealie
      - POSTGRES_SERVER=meal-pg.home
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mealie
    labels:
      - "coredns.dockerdiscovery.host=meal.home"
    networks:
      app-network:
        ipv4_address: 192.168.40.26
    dns:
      - 192.168.40.5
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    volumes:
      - mealie-pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mealie
      POSTGRES_USER: mealie
      PGUSER: mealie
    labels:
      - "coredns.dockerdiscovery.host=meal-pg.home"
    networks:
      app-network:
        ipv4_address: 192.168.40.27
    dns:
      - 192.168.40.5
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  mealie-data:
  mealie-pgdata:

networks:
  app-network:
    external: true
