volumes:
  n8n:

services:
  n8n:
    container_name: n8n
    image: n8nio/n8n:1.82.3
    restart: always
    environment:
      - DB_TYPE
      - DB_POSTGRESDB_DATABASE
      - DB_POSTGRESDB_HOST
      - DB_POSTGRESDB_PORT
      - DB_POSTGRESDB_USER
      - DB_POSTGRESDB_PASSWORD
      - DB_POSTGRESDB_SCHEMA
      - N8N_LOG_LEVEL
      - N8N_SECURE_COOKIE
      - N8N_HOST
      - N8N_PORT
    ports:
      - 5678:5678
    volumes:
      - n8n:/home/node/.n8n
    labels:
      - "coredns.dockerdiscovery.host=n8n.home"
    dns:
      - 192.168.40.5
    networks:
      app-network:
        ipv4_address: 192.168.40.6

networks:
  app-network:
    external: true
