services:
  coredns:
    image: coredns/coredns
    container_name: coredns
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - /var/home/core/coredns/Corefile:/Corefile:ro
      - /var/home/core/coredns/zones:/zones:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
