services:
  test-service:
    image: nginx
    container_name: test
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.test.loadbalancer.server.port=80"
      - "traefik.http.routers.test.rule=Host(`test.home`)"
      - "coredns.dockerdiscovery.host=test.home"
    networks:
      - app-network

networks:
  app-network:
    external: true
