services:
  test-service:
    image: nginx
    container_name: test-web
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.test.loadbalancer.server.port=80"
      - "traefik.http.routers.test.rule=Host(`test-web.home`)"
      - "coredns.dockerdiscovery.host=test-web.home"
    dns:
      - 192.168.40.5
    networks:
      - app-network

networks:
  app-network:
    external: true
