services:
  test-service:
    image: nginx
    container_name: test-web
    labels:
      - "coredns.dockerdiscovery.host=test-web.home"
    dns:
      - 192.168.40.5
    networks:
      app-network:
        ipv4_address: 192.168.40.10

networks:
  app-network:
    external: true
