services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.48.2
    container_name: playwright
    hostname: webdriver
    shm_size: 2g
#     ports:   # not needed for macvlan
#       - "3000:3000"  # Playwright web server port
#       - "9323:9323"  # Debugging port
    volumes:
      - playwright_data:/home/pwuser
    restart: unless-stopped
    labels:
      - "coredns.dockerdiscovery.host=playa.home"
    dns:
      - 192.168.40.5
    networks:
      app-network:
        ipv4_address: 192.168.40.21
    environment:
      # Enable Playwright to run browsers in headless mode
      - DISPLAY=:0
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
    command: /bin/sh -c "cd /ms-playwright && PLAYWRIGHT_BROWSERS_PATH=/ms-playwright npx -y playwright@1.48.2 run-server --port 3000 --host 0.0.0.0"
    user: pwuser

volumes:
  playwright_data:

networks:
  app-network:
    external: true
