services:
  nginx:
    image: nginx:1.27.4
    container_name: nginx
    volumes:
      - /var/home/core/nginx/html:/usr/share/nginx/html:ro
      - /var/home/core/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    labels:
      - "coredns.dockerdiscovery.host=web.home"
    dns:
      - 192.168.40.5
    networks:
      app-network:
        ipv4_address: 192.168.40.9

networks:
  app-network:
    external: true
