services:
  swagger-editor:
    image: swaggerapi/swagger-ui:v5.20.2
    container_name: swagger-ui
    restart: unless-stopped
    #ports:    # not needed for macvlan
    #  - "80:8080"
    environment:
      - "PORT=80"
    labels:
      - "coredns.dockerdiscovery.host=swui.home"
    dns:
      - 192.168.40.5
    networks:
      app-network:
        ipv4_address: 192.168.40.31

networks:
  app-network:
    external: true
