services:
  postgres:
    container_name: jenkins
    image: jenkins/jenkins:2.508
    restart: unless-stopped
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "coredns.dockerdiscovery.host=jenkins.home"
    dns:
      - 192.168.40.5
    networks:
      app-network:
        ipv4_address: 192.168.40.8

volumes:
  jenkins-data:
    external: true

networks:
  app-network:
    external: true
