services:
  swagger-editor:
    image: docker.swagger.io/swaggerapi/swagger-editor:next-v5
    container_name: swagger-editor
    restart: unless-stopped
    #ports:    # not needed for macvlan
    #  - "80:8080"
    environment:
      - "PORT=80"
    labels:
      - "coredns.dockerdiscovery.host=swed.home"
    dns:
      - 192.168.40.5
    networks:
      app-network:
        ipv4_address: 192.168.40.30

networks:
  app-network:
    external: true
