services:
  portainer:
    # image: portainer/portainer:linux-amd64-2.0.1
    image: portainer/portainer-ce:2.26.1-linux-amd64-alpine
    container_name: portainer
    hostname: port
    entrypoint: /portainer -p :443
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 443:9443
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.test.loadbalancer.server.port=443"
      - "traefik.http.routers.test.rule=Host(`port.home`)"
      - "coredns.dockerdiscovery.host=port.home"
    dns:
      - 192.168.40.5
    networks:
      app-network:
        ipv4_address: 192.168.40.3

volumes:
  portainer_data:
    external: true

networks:
  app-network:
    external: true
