services:
  changedetection:
    image: dgtlmoon/changedetection.io:0.49.13
    container_name: changedetection
    hostname: changes
    volumes:
      - chgdet_data:/datastore
    restart: unless-stopped
    environment:
      - PORT=80
      - BASE_URL=/
      # Allows you to handle large webpage snapshots
      - FETCH_WORKERS=8
      - MAX_REQUESTS_PER_WORKER=10
      # Default time between checks (in seconds)
      - CHECK_INTERVAL=3600
      - PLAYWRIGHT_DRIVER_URL=ws://${BROWSERLESS_HOST}:3000/?token=${BROWSERLESS_TOKEN}&--disable-web-security=true&timeout=120000&blockAds=true
    labels:
      - "coredns.dockerdiscovery.host=changes.home"
    dns:
      - 192.168.40.5
    networks:
      app-network:
        ipv4_address: 192.168.40.2

volumes:
  chgdet_data:
    external: true

networks:
  app-network:
    external: true
