services:
  changedetection:
    image: dgtlmoon/changedetection.io:0.49.0
    container_name: changedetection
    hostname: changes
    volumes:
      - chgdet_data:/datastore
    # ports:
    #   - 5000:5000
    restart: unless-stopped
    environment:
      # - PORT=5000
      - PORT=80
      - BASE_URL=/
      # Allows you to handle large webpage snapshots
      - FETCH_WORKERS=4
      - MAX_REQUESTS_PER_WORKER=10
      # Default time between checks (in seconds)
      - CHECK_INTERVAL=3600
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.test.loadbalancer.server.port=80"
      - "traefik.http.routers.test.rule=Host(`changes.home`)"
      - "coredns.dockerdiscovery.host=changes.home"
    dns:
      - 192.168.40.5
    networks:
      app-network:
        ipv4_address: 192.168.40.6

volumes:
  chgdet_data:
    external: true

networks:
  app-network:
    external: true
