---
# For more examples, see: https://gethomepage.dev/latest/configs/services/

- Docker hosts:
    - NUC1:
        icon: si-docker
        description: Primary
        href: http://port.home:443/#!/1/docker/dashboard
        ping: nuc1.home
        widget:
          type: glances
          url: http://glances.home:61208
          version: 4 
          metric: cpu
          pointsLimit: 45

    - Raspberry Pi:
        icon: mdi-raspberry-pi
        description: Pi 4
        ping: pi4.home
        
    - AWS:
        icon: si-amazonec2
        description: Cloud Jobs
        href: http://port.home:443/#!/2/docker/dashboard
        ping: jobs.billbaran.us
        widget:
          type: glances
          url: http://jobs.billbaran.us:61208
          version: 4 
          metric: cpu
          pointsLimit: 45

- Applications:
    - Open WebUI:
        icon: si-ollama
        href: http://llm.home
        description: LLM interface
        siteMonitor: http://llm.home
      
    - n8n:
        icon: si-n8n
        href: http://n8n.home
        description: Workflow automation
        siteMonitor: http://n8n.home
      
    - Change Detection:
        icon: sh-changedetection
        href: http://changes.home
        description: Website change monitoring
        siteMonitor: http://changes.home
      
    - Browserless:
        icon: /icons/browserless-light.svg
        iconStyle: flat
        href: http://browserless.home:3000/
        description: Browser automation
        siteMonitor: http://browserless.home:3000/

    - Jenkins:
        icon: si-jenkins
        href: http://jenkins.home:8080
        description: CI/CD pipeline
        siteMonitor: http://jenkins.home:8080

    - Home Assistant:
        icon: si-homeassistant
        href: http://ctrl.home:8123
        description: Home automation platform
        siteMonitor: http://ctrl.home:8123
        
    - node-red:
        icon: si-nodered
        href: http://nred.home:1880/
        description: Visual IoT orchestration
        siteMonitor: http://n8n.home
      
- Services:
    - Portainer:
        icon: si-portainer
        href: http://port.home:443
        description: Docker management
        siteMonitor: http://port.home:443
        
    - slzb-06:
        icon: si-zigbee
        description: Zigbee Coordinator
        siteMonitor: http://192.168.50.76/
        
    - CoreDNS:
        icon: mdi-dns
        description: DNS server
        ping: coredns.home
      
    - IT-Tools:
        icon: it-tools-light
        description: IT Tools
        ping: itt.home
      
    - RabbitMQ:
        icon: si-rabbitmq
        href: http://rmq.home:15672/
        description: Message Queue
        siteMonitor: http://rmq.home:15672

    - Nginx:
        icon: si-nginx
        href: http://web.home
        description: Web server
        siteMonitor: http://web.home
        
    - Wireguard:
        icon: si-wireguard
        href: http://vpn.home:51821/
        description: VPN server
        siteMonitor: http://vpn.home:51821

- Databases:
    - TimescaleDB:
        id: timescale
        icon: /icons/timescale.svg
        iconStyle: flat
        ping: psql.home
        description: Relational DB
      
    - Minio:
        icon: si-minio
        href: http://minio.home:9001/login
        description: Object DB
        siteMonitor: http://minio.home:9001/login
        
    - Qdrant:
        icon: /icons/qdrant-icon.png
        href: http://qdrant.home:6333/dashboard/#/collections
        description: Vector DB
        siteMonitor: http://qdrant.home:6333
      
    - Valkey:
        icon: sh-valkey-light
        description: Key/Value Stor
        ping: key.home
      
    - Mongo:
        icon: si-mongodb
        description: Document DB
        ping: mongo.home

- External:
    - ntfy:
        icon: si-ntfy
        href: https://ntfy.billbaran.us
        description: Notification service
        siteMonitor: https://ntfy.billbaran.us

    - traefik:
        icon: si-traefikproxy
        href: https://jobs.billbaran.us
        description: Reverse Proxy
        siteMonitor: https://jobs.billbaran.us

    - router:
        icon: si-republicofgamers
        href: https://192.168.50.1:8443/Main_Login.asp
        description: WAN Router
        siteMonitor: https://192.168.50.1:8443/
