---
# Define widget configurations for Homepage
# Create this as a new file: widgets.yaml in your config directory

- resources:
    cpu: true
    memory: true
    uptime: true
    units: imperial
    disk: /mnt/host-var   

#- openweathermap:
#    label: Boise  # optional
#    latitude: 43.614
#    longitude: -116.298
#    units: imperial # or imperial
#    provider: openweathermap
#    #apiKey: youropenweathermapkey # required only if not using provider, this reveals api key in requests
#    cache: 5 # Time in minutes to cache API responses, to stay within limits
#    format: # optional, Intl.NumberFormat options
#      maximumFractionDigits: 1

- openmeteo:
    label: Boise  # optional
    latitude: 43.614
    longitude: -116.298
    timezone: America/Denver # optional
    units: imperial # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1
