services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    environment:
      - APP_ENV
      - APP_DEBUG
      - SITE_OWNER
      - APP_KEY
      - DEFAULT_LANGUAGE
      - DEFAULT_LOCALE
      - TZ
      - TRUSTED_PROXIES
      - LOG_CHANNEL
      - APP_LOG_LEVEL
      - AUDIT_LOG_LEVEL
      - AUDIT_LOG_CHANNEL
      - PAPERTRAIL_HOST
      - PAPERTRAIL_PORT
      - DB_CONNECTION
      - DB_HOST
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - DB_SOCKET
      - MYSQL_USE_SSL
      - MYSQL_SSL_VERIFY_SERVER_CERT
      - MYSQL_SSL_CAPATH
      - MYSQL_SSL_CA
      - MYSQL_SSL_CERT
      - MYSQL_SSL_KEY
      - MYSQL_SSL_CIPHER
      - PGSQL_SSL_MODE
      - PGSQL_SSL_ROOT_CERT
      - PGSQL_SSL_CERT
      - PGSQL_SSL_KEY
      - PGSQL_SSL_CRL_FILE
      - PGSQL_SCHEMA
      - CACHE_DRIVER
      - SESSION_DRIVER
      - REDIS_SCHEME
      - REDIS_PATH
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_USERNAME
      - REDIS_PASSWORD
      - REDIS_DB
      - REDIS_CACHE_DB
      - COOKIE_PATH
      - COOKIE_DOMAIN
      - COOKIE_SECURE
      - COOKIE_SAMESITE
      - MAIL_MAILER
      - MAIL_HOST
      - MAIL_PORT
      - MAIL_FROM
      - MAIL_USERNAME
      - MAIL_PASSWORD
      - MAIL_ENCRYPTION
      - MAIL_SENDMAIL_COMMAND
      - MAILGUN_DOMAIN
      - MAILGUN_SECRET
      - MAILGUN_ENDPOINT
      - MANDRILL_SECRET
      - SPARKPOST_SECRET
      - MAILERSEND_API_KEY
      - SEND_ERROR_MESSAGE
      - SEND_REPORT_JOURNALS
      - ENABLE_EXTERNAL_MAP
      - ENABLE_EXCHANGE_RATES
      - ENABLE_EXTERNAL_RATES
      - MAP_DEFAULT_LAT
      - MAP_DEFAULT_LONG
      - MAP_DEFAULT_ZOOM
      - VALID_URL_PROTOCOLS
      - AUTHENTICATION_GUARD
      - AUTHENTICATION_GUARD_HEADER
      - AUTHENTICATION_GUARD_EMAIL
      - PASSPORT_PRIVATE_KEY
      - PASSPORT_PUBLIC_KEY
      - CUSTOM_LOGOUT_URL
      - DISABLE_FRAME_HEADER
      - DISABLE_CSP_HEADER
      - TRACKER_SITE_ID
      - TRACKER_URL
      - ALLOW_WEBHOOKS
      - STATIC_CRON_TOKEN
      - DKR_BUILD_LOCALE
      - DKR_CHECK_SQLITE
      - APP_NAME
      - BROADCAST_DRIVER
      - QUEUE_DRIVER
      - CACHE_PREFIX
      - PUSHER_KEY
      - IPINFO_TOKEN
      - PUSHER_SECRET
      - PUSHER_ID
      - DEMO_USERNAME
      - DEMO_PASSWORD
      - USE_RUNNING_BALANCE
      - FIREFLY_III_LAYOUT
      - QUERY_PARSER_IMPLEMENTATION
      - APP_URL
    networks:
      firefly_iii: {}
      app-network:
        ipv4_address: 192.168.40.14
    dns:
      - 192.168.40.5
    #ports:  # Not needed for macvlan
    #  - 80:8080
    labels:
      - "coredns.dockerdiscovery.host=ff3.home"
    depends_on:
      - db
  db:
    image: mariadb:lts
    hostname: db
    container_name: firefly_iii_db
    restart: always
    env_file: .db.env
    networks:
      - firefly_iii
    volumes:
      - firefly_iii_db:/var/lib/mysql
  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    restart: always
    container_name: firefly_iii_cron
    env_file: .env
    command: sh -c "
      apk add tzdata
      && ln -s /usr/share/zoneinfo/${TZ} /etc/localtime
      | echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/${STATIC_CRON_TOKEN};echo\" 
      | crontab - 
      && crond -f -L /dev/stdout"
    networks:
      - firefly_iii

volumes:
   firefly_iii_upload:
   firefly_iii_db:

networks:
  firefly_iii:
    driver: bridge
  app-network:
    external: true
