volumes:
  postgres_data:

services:
  postgres:
    container_name: psql
    image: postgres:16
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /var/home/core/psql/init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.test.loadbalancer.server.port=80"
      - "traefik.http.routers.test.rule=Host(`psql.home`)"
      - "coredns.dockerdiscovery.host=psql.home"
    dns:
      - 192.168.40.5
    networks:
      app-network:
        ipv4_address: 192.168.40.7

networks:
  app-network:
    external: true
